### PR TITLE
Upgrade CKEditor to version 4.17.2 #1518

### PR DESCRIPTION
**Pull request by ashklianko**

### CODE REVIEW

**Comment by ashklianko** [comment]
Codacy complains about cke files, may be skipped

**Review by alansemenov — CHANGES_REQUESTED** [review]
Great stuff, but we definitely don't need the `samples` folder.

**Comment by ashklianko** [comment]
will remove, also will add numbered list properties in this pull

**Comment by ashklianko** [comment]
Done, list properties are available via context menu (right click on list)

**Review by alansemenov — APPROVED** [review]
Yippee!

**Pull request merged**
