### PR TITLE
Apply button in the Inspect panel shouldn't save content when no chan…

### PR DESCRIPTION
**Pull request by ashklianko**
…ges have been made #2151

### CODE REVIEW

**Review by alansemenov — CHANGES_REQUESTED** [review]
It can be reproduced quite easily, actually. Just keep selecting the text component and clicking Apply. (Why we have Apply there at all is another issue.) Good thing that it doesn't create a new version because I guess there's some smartness on the server that checks whether content has changed, but we shouldn't try to save it on the client either.

It also loses component selection after save, which is another bug...

https://user-images.githubusercontent.com/11612490/117281254-bf55d200-ae63-11eb-9500-7aed7cd6a091.mov

**Comment by ashklianko** [comment]
Updated

**Review by alansemenov — APPROVED** [review]

**Comment by sigdestad** [comment]
Did we manage to remove/disable apply button if nothing was changed?

**Comment by ashklianko** [comment]
Not yet, that would be a separate issue, however we've fixed some general issue with saving content

**Pull request merged**
