### PR TITLE
Enable marking all items in "In progress" state as "Ready" #2530

### PR DESCRIPTION
**Pull request by ashklianko**
Requires https://github.com/enonic/lib-admin-ui/pull/1588

### CODE REVIEW

**Comment by alansemenov** [comment]
This will have to be reworked once https://github.com/enonic/xp/issues/8485 is done

**Review by alansemenov — CHANGES_REQUESTED** [review]
Fantastic job, Sasha! One small thing to fix: required items (those with ids in the `requiredContents` field of the API response) should be excluded from the number in "`Exclude all (X)`" link, and shouldn't be added to `excludedIds` field when sending the response.

In the example below there are 2 in progress items, but one of them is required for publishing. In this case the link should say "_Exclude all (1)_", and we should not attempt to exclude the second item from publishing when the link is clicked.

image

**Comment by ashklianko** [comment]
Updated!

**Comment by sigdestad** [comment]
Hmm.. Alan, this is positively wrong IMHO. 
In this case (where there are 2 in progress items) we should exactly say "exclude all (2)"

You cannot really know how many items are "required" or not until you try removing all "in progress".

**Comment by alansemenov** [comment]
What do you mean? Of course we know how many are required or not in the current list.

**Comment by sigdestad** [comment]
I mean, we will attempt to remove them all, regardless of if the current state says some of them are required

**Comment by sigdestad** [comment]
This is the whole point of the task..

**Comment by sigdestad** [comment]
Also, what I mean is that when you attempt to remove all, it might happen that some end up being required anyway (i.e. parent of selected)

**Comment by alansemenov** [comment]
Why "attempt" anything there? We know exactly how many we can exclude, that's how we know which "x" icons to disable. Obviously after each exclusion the number can change, but we always know how many we can exclude at any given moment. If it says "Exclude all (1)" for one invalid item that cannot be excluded and nothing happens when you click the link, this is obviously a bad UX. 

Another alternative is to always show the total number of items to exclude but disable the link if none of the items can be excluded.

**Comment by sigdestad** [comment]
So, how many times do you want me to click “exclude all“ then?

**Comment by alansemenov** [comment]
Just once. There will never be a case when you will get **more** items to exclude than you originally had. Let's try it out and if we encounter some side issues then we'll consider other alternatives.

**Comment by alansemenov** [comment]
Remember that we refresh these numbers after each exclusion. So if for example some "in progress" items were required by some "invalid" items, then the number in "Exclude all (X)" for the "in progress" items will be recalculated after you excluded the invalid ones and vice versa.

**Comment by sigdestad** [comment]
The idea is that you press the button _once_. If there are any items left after this, they cannot be removed (parent items of Main items that have never been published)

**Comment by alansemenov** [comment]
> The idea is that you press the button once. If there are any items left after this, they cannot be removed (parent items of Main items that have never been published)

That is exactly what I wrote in the original comment. Items that cannot be excluded should not be a part of X in the "_Exclude all (X)_" link. Because they cannot be excluded.

**Comment by sigdestad** [comment]
We'll have to take this F2F

**Comment by alansemenov** [comment]
To sum up the changes:

1. Show total number of "in progress"/"invalid" items in the corresponding links
2. Always add all corresponding ids to `excludedIds` field of the API request when the link is clicked
3. Check if there are any items that were **not** excluded after receiving API response. If there's at least one item that was not excluded, give a warning (yellow toast popup) saying "Some of the items are required for publishing and could not be excluded" and hide the corresponding link.

**Comment by ashklianko** [comment]
Updated

**Review by alansemenov — APPROVED** [review]

**Pull request merged**
