### PR TITLE
Add rendering mode param to IsRenderableRequest #4347

### PR DESCRIPTION
**Pull request by pmi**

### CODE REVIEW

**Review by alansemenov — CHANGES_REQUESTED** [review]
@pmi I don't like the idea of always sending the `mode` parameter, even if it's not used. Let's make `mode` an optional argument in the constructor, remove the default value and append `mode` to params only when it's set.

**Comment by sigdestad** [comment]
Any reason why we don't make this a header instead?

**Comment by alansemenov** [comment]
> Any reason why we don't make this a header instead?

Because we are already making Content Studio & NextJS starter tightly coupled.

**Comment by sigdestad** [comment]
I'm just saying that a parameter is more intrusive than header, next.js should eat whatever we throw at it. Anyway, this is a temporary workaround until page editor gets more flexible - right?

**Comment by alansemenov** [comment]
> Anyway, this is a temporary workaround until page editor gets more flexible - right?

Until XP stops returning 200 for a page that cannot in fact be edited, yes.

**Review by alansemenov — APPROVED** [review]

**Pull request merged**
