### PR TITLE
Project and layers DAG visualization #5482

### PR DESCRIPTION
**Pull request by reisfmb**

### CODE REVIEW

**Comment by reisfmb** [comment]
@alansemenov 

PR is in draft because it remains to fix some things... some of those things are code related, while others are feature related, such as refreshing the visualization after adding a new project / layer. Currently there's the need to highlight again the project item in the tree grid.

Feel free to test it locally :)

**Review by alansemenov — CHANGES_REQUESTED** [review]
1. Container of the graph has incorrect dimensions which makes it look bad (see the screenshot below - connecting lines go out of the view). It seems that you are using width of the entire page for `svg-container` but you should use width of the preview panel (even a bit less, so that lines never touch the panel borders). Actually, after checking it a bit more, it seems that the width and height are hardcoded (2000px and 600px), but they should dynamically change based on width/height of the preview panel. See examples using `ResponsiveManager` in the code.

image

2. There's no difference in line thickness based on whether parent is "main" or not. All the lines have the same thickness.

3. Lots of Codacy issues which can be seen [here](https://github.com/enonic/app-contentstudio/pull/5547/files#diff-a304fab231d4b70e9c34b3540c1a00e645605aa64ca46c5285c458cc4b4395f0). Seems like you indented with a tab, but it should be two spaces.

**Comment by reisfmb** [comment]
@alansemenov 

1. They are not actually hardcoded, but calculated. Different dags will have different widths / heights. But the problem is that this calculation was actually wrong. Fixed it.

2. This is working, but I think you couldn't see it because the visualization was out of screen. Paths connecting projects to layers will have `stroke-weight` of 3, while other will have `stroke-weight` of 2.

3. Will check Codacy before converting this PR from draft to ready.

I've implemented some fixes + improvements on node positioning + paths. Here's an example of how it is looking:

image

Could you please test it again?

**Review by alansemenov — APPROVED** [review]
Great job, Bruno!

**Pull request merged**
