### PR TITLE
Enable non-breaking space plugin in HTML Editor

### LINKED ISSUE #5564: Enable non-breaking space plugin in HTML Editor
https://ckeditor.com/cke4/addon/nbsp

### PR DESCRIPTION
**Pull request by alansemenov**

### CODE REVIEW

**Comment by ashklianko** [comment]
image

NBSP is not visible in the special chars dialog until there's a mouse hover over it

**Comment by alansemenov** [comment]
> NBSP is not visible in the special chars dialog until there's a mouse hover over it

Any suggestions on how to visualise it? The main idea of this task is to make nbsp insertable with Alt-Space shortcut. Adding it to the special char dialog is just an extra-measure.

**Comment by ashklianko** [comment]
> > NBSP is not visible in the special chars dialog until there's a mouse hover over it
> 
> Any suggestions on how to visualise it? The main idea of this task is to make nbsp insertable with Alt-Space shortcut. Adding it to the special char dialog is just an extra-measure.

Yes, to use text `sp`  for a spec symbol 
image
and then replace it with required `&nbsp;` on insert in `SpecialCharDialog`

**Comment by alansemenov** [comment]
Done

**Review by ashklianko — APPROVED** [review]

**Pull request merged**
