### PR TITLE
Improved focus in the first project of the 'select project' dialog (#3943)

### PR DESCRIPTION
**Pull request by reisfmb**

### CODE REVIEW

**Review by ashklianko — CHANGES_REQUESTED** [review]
TAB is working OK, but Shift+TAB on the last element will still move focus to the first element, not the one before last

**Comment by ashklianko** [comment]
One more question: do we need those `setTimeout `functions wrappers around keydown handlers?

**Comment by reisfmb** [comment]
> One more question: do we need those `setTimeout `functions wrappers around keydown handlers?

Yes, tried without them before and it wasn't working properly.

**Comment by ashklianko** [comment]
Was fixed in https://github.com/enonic/lib-admin-ui/issues/2321

**Pull request closed without merging**
