### PR TITLE
Fixed workflow icon

### PR DESCRIPTION
**Pull request by alansemenov**

### CODE REVIEW

**Comment by alansemenov** [comment]
@reisfmb we need to mitigate the issue described in the [original PR](https://github.com/enonic/app-contentstudio/pull/4768#issuecomment-1172117294) causing the UI tests to fail. I'm closing the other one.

**Comment by reisfmb** [comment]
@alansemenov 

I've implemented a better fix. Seems to be working fine. Messaged @sgauruseu to better understand why those [two tests](https://github.com/enonic/app-contentstudio/runs/7508290100?check_suite_focus=true#step:7:7062) are still failing.

**Comment by reisfmb** [comment]
> @reisfmb we need to mitigate the issue described in the [original PR](https://github.com/enonic/app-contentstudio/pull/4768#issuecomment-1172117294) causing the UI tests to fail. I'm closing the other one.

I've implemented a better fix. Seems to be working fine, but there are still [two failing tests](https://github.com/enonic/app-contentstudio/runs/7508290100?check_suite_focus=true#step:7:7062)... since I couldn't reproduce them (maybe I've misunderstood what is being tested), I've messaged @sgauruseu to better understand why they're failing.

**Comment by reisfmb** [comment]
> > @reisfmb we need to mitigate the issue described in the [original PR](https://github.com/enonic/app-contentstudio/pull/4768#issuecomment-1172117294) causing the UI tests to fail. I'm closing the other one.
> 
> I've implemented a better fix. Seems to be working fine. Messaged @sgauruseu to better understand why those [two tests](https://github.com/enonic/app-contentstudio/runs/7508290100?check_suite_focus=true#step:7:7062) are still failing, since I couldn't reproduce them (maybe I've misunderstood what is being tested)

**Pull request closed without merging**
