### PR TITLE
Show inheritance option in the Sorting dialog #2215

### PR DESCRIPTION
**Pull request by ashklianko**

### CODE REVIEW

**Comment by ashklianko** [comment]
https://github.com/enonic/lib-admin-ui/pull/1456 also required

**Review by alansemenov — CHANGES_REQUESTED** [review]
Tested it now, and there are issues when item has "local" sorting and I want to reset to "inherited":

1. If "local" sorting is the same as "inherited" sorting, Save button remain disabled when I select "Inherited: " option.

Screenshot 2020-09-15 at 16 16 20

2. If "local" and "inherited" sorting are different, I can select "Inherited" option and Save but it won't call the API to "restore" the sorting inheritance. When I reopen the dialog it shows the new sorting type, but as "local", not "inherited":

image

**Comment by alansemenov** [comment]
So basically https://github.com/enonic/app-contentstudio/issues/2218 is not completely done yet

**Comment by alansemenov** [comment]
`restoreInherit` API is [ready](https://github.com/enonic/xp/issues/8303)

**Comment by ashklianko** [comment]
Ok, will update

**Comment by ashklianko** [comment]
Updated

**Review by alansemenov — CHANGES_REQUESTED** [review]
One last bug: it's not possible to switch between inherited and non-inherited for the same sort option, for example from "_Display name: A->Z_" to "_Inherited: Display name: A->Z_" and vice versa.

**Comment by ashklianko** [comment]
> One last bug: it's not possible to switch between inherited and non-inherited for the same sort option, for example from "_Display name: A->Z_" to "_Inherited: Display name: A->Z_" and vice versa.

Done

**Pull request merged**
