### PR TITLE
Move button opening AI Assitant to the right bottom corner #7454

### LINKED ISSUE #7454: Move button opening AI Assitant to the right bottom corner
Should be here:
image

### PR DESCRIPTION
**Pull request by ashklianko**

### CODE REVIEW

**Comment by ashklianko** [comment]
Requires https://github.com/enonic/app-saga/pull/160

**Review by alansemenov — APPROVED** [review]

**Comment by edloidas** [comment]
IMHO, bottom right action button is actually a cancer of Google material design.
The button came from mobile-first idea, where that button located next to big finger in ugly Google apps. Then it disappeared as quickly as appeared. The location of the button is not "most logical", but rather "most annoying". It takes up more space than it needs and than it could.

I highly recommend returning it to where the rest of the active elements are located between the pages. 
The argument that it will be difficult to find stops working immediately after the first click and is corrected by the initial presentation.

**Comment by ashklianko** [comment]
@edloidas what is your thought on the most suitable place for this button then? Same as it was before?

**Comment by ashklianko** [comment]
Leaving the button as it is until a better spot is found

**Pull request closed without merging**
