### PR TITLE
Improved styling of regions inside Page Components view

### LINKED ISSUE #7290: Improved styling of regions inside Page Components view
Regions should be styled differently than other nodes in the Page Components view: 
* Remove subtitle, keep only display name
* Change color
* Make a double-click expand/collapse (any) node

image

### PR DESCRIPTION
**Pull request by alansemenov**

### CODE REVIEW

**Comment by ashklianko** [comment]
Couple issues I see in this updated design:

1. Region name is not aligned with expand/collapse arrow, an eye catches it immediately:
image

2. Empty regions look alien, while page components have icon and subtitle it only has display name, nothinbg tells what it is:
image

**Review by ashklianko — CHANGES_REQUESTED** [review]
Need to discuss the look of the updated region

**Comment by alansemenov** [comment]
Alignment is fixed
image

**Comment by alansemenov** [comment]
Updated

image

**Pull request merged**
